apiVersion: v1
kind: Secret
metadata:
  name: ${SECRET_NAME}
type: Opaque
stringData:
  CONNECTION_URL: ${CONNECTION_URL}
  SCHEMA_PATERN: ${SCHEMA_PATERN}
  CONNECTION_USER: ${CONNECTION_USER}
  CONNECTION_PASSWORD: ${CONNECTION_PASSWORD}
  STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
  STORAGE_SECRET_ACCESS_KEY: ${STORAGE_SECRET_ACCESS_KEY}
  BUCKET_NAME: ${BUCKET_NAME}
